#!/bin/sh
#
# avahi-daemon:	Starts the Avahi daemon
#
# chkconfig:	345 34 66
#
# description:	This is a daemon which runs on client machines to perform \
#		Zeroconf service discovery on a network. avahi-daemon must be \
#		running on systems  that use Avahi for service discovery. \
#		Avahi-daemon should not be running otherwise.
#

# Source function library
. /etc/rc.d/init.d/functions

# Get network config
. /etc/sysconfig/network

# Check that networking is up.
if is_yes "${NETWORKING}"; then
	if [ ! -f /var/lock/subsys/network ]; then
		msg_network_down avahi-daemon
		exit 1
	fi
else
	exit 0
fi


# See how we were called.
case "$1" in
  start)
	# Check if the service is already running?
	if [ ! -f /var/lock/subsys/avahi-daemon ]; then
		msg_starting avahi-daemon
		daemon avahi-daemon -D
		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/avahi-daemon
	else
		msg_already_running avahi-daemon
	fi
	;;
  stop)
	if [ -f /var/lock/subsys/avahi-daemon ]; then
		# Stop daemons.
		msg_stopping avahi-daemon
		avahi-daemon -k
		rm -f /var/lock/subsys/avahi-daemon
		ok
	else
		msg_not_running avahi-daemon
	fi
	;;
  restart)
	$0 stop
	$0 start
	exit $?
	;;
  reload)
	if [ -f /var/lock/subsys/avahi-daemon ]; then
		msg_reloading avahi-daemon
		avahi-daemon -r
		RETVAL=$?
	else
		msg_not_running avahi-daemon >&2
		RETVAL=7
	fi
	;;
  force-reload)
	$0 reload
	exit $?
	;;
  status)
	status avahi-daemon
	RETVAL=$?
	;;
  *)
	msg_usage "$0 {start|stop|restart|reload|force-reload|status}"
	exit 3
esac

exit $RETVAL

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4
